name: Build and Deploy

on:
  push:
    branches:
      - main
#enterd main as github configuration is missing in local system, deployment is getting failed. In order to mke it work, need to give the branch which need to deployed and need to configure git in local system

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        if: matrix.os == 'windows-latest'
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Deploy
        run: npm run deploy
